export const STORAGE_USER_AUTH_TYPE = "__AUTH_TYPE__";
export const STORAGE_USER_AUTH_TOKEN = "__AUTH_TOKEN__";
export const STORAGE_USER_AUTH_CUSTOMER_INFO = "__AUTH_CUSTOMER_INFO__";
export const SET_USER_AUTH_TYPE = "SET_USER_AUTH_TYPE";
export const SET_USER_AUTH_TOKEN = "SET_USER_AUTH_TOKEN";
export const SET_USER_AUTH_CUSTOMER_INFO = "SET_USER_AUTH_CUSTOMER_INFO";